spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类名
    url: jdbc:mysql://106.54.9.19:5432/springcloudtestdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC  # 数据库连接 URL
    username: root  # 数据库用户名
    password: biaoge666  # 数据库密码
    hikari:
      maximum-pool-size: 20  # 连接池最大连接数
      minimum-idle: 5  # 连接池最小空闲连接数
      connection-timeout: 30000  # 连接超时时间，30秒
      idle-timeout: 600  # 空闲连接超时时间，10分钟
      max-lifetime: 1800  # 连接最大生存时间，30分钟
  main:
    allow-bean-definition-overriding: true