spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]': # 匹配所有的请求路径
            allowedOrigins: # 允许哪些网站的跨域请求
              - "*" # 允许所有
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      routes:
      - id: user-service
        uri: lb://test-user # 路由的目标地址 http就是固定地址
        predicates:
          - Path=/api/user/** # 这个是匹配规则，只要以/user/开头就会符合要求
      - id: product-service
        uri: lb://test-product # 路由的目标地址 http就是固定地址
        predicates:
          - Path=/api/product/** # 这个是匹配规则，只要以/user/开头就会符合要求
      default-filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment} # 默认的过滤器,将所有的请求的/api去掉

